#!/bin/bash
# chkconfig: - 81 15
# description: metric reporter

. /etc/rc.d/init.d/functions

ALREADY_RUN=111
RETVAL=1
prog="reductor metric grabber"
PROG="${0##*/}"
LOCKFILE="/var/lock/subsys/$PROG"
start() {
	#skip_if_disabled "$PROG"
	echo -n $"Starting $prog: "
	[ -s /var/run/$PROG.pid ] && return 0
	setsid /opt/reductor_influxdb_agent/bin/$PROG >>/var/log/$PROG.log 2>&1 & disown -a
	RETVAL=$?
	pid=$!
	if [ "$RETVAL" = '0' ]; then
		echo $pid >/var/run/$PROG.pid
		touch $LOCKFILE
	fi
	[ "$RETVAL" != "0" ] && rm -f $LOCKFILE /var/run/$PROG.pid
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	# killproc $PROG 2>/dev/null
	[ -s /var/run/$PROG.pid ] && kill  $(</var/run/$PROG.pid)
	RETVAL=$?
	rm -f $LOCKFILE /var/run/$PROG.pid
	return $RETVAL
}

echo_result() {
	if [ "$1" = '0' ]; then
		echo_success
	else
		echo_failure
	fi
	echo
	return $1
}

# See how we were called.
case "$1" in
	start)
		start
		RETVAL=$?
		echo_result $RETVAL
		;;
	stop)
		stop
		RETVAL=$?
		echo_result $RETVAL
		;;
	restart)
		stop
		RETVAL=$?
		echo_result $RETVAL
		start
		RETVAL=$?
		echo_result $RETVAL
		;;
	condrestart)
		[ -e "$LOCKFILE" ] && restart
		RETVAL=$?
		;;
	status)
		status -p /var/run/$PROG.pid
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|condrestart}"
		exit 1
		;;
esac
exit $RETVAL
